name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  DOTNET_VERSION: "9.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore Eventix.sln

    - name: Build
      run: dotnet build Eventix.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test Eventix.sln --configuration Release --no-restore --no-build